### ISSUE TITLE
HTTPClient (TinyGo) returns 0 length response

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/capability-providers#67] opened 2021-04-02 19:46 UTC
Running down the `range error` issue with the `httpclient` actor, the host is returning 0 bytes and causing the error.  

The error is returned here: 
https://github.com/jordan-rash/actor-interfaces/blob/f5cec8111a977cef4be6077eb095c96776b0f1f6/http-client/go/httpclient.go#L184

It bubbles up from the `GetUInt8` function that is being called from the code above. 
https://github.com/wapc/tinygo-msgpack/blob/master/data_reader.go#L113

Having added some additional debug points, I short circuited the `HostCall` at 
https://github.com/wapc/wapc-guest-tinygo/blob/f05bbfb9b3f4bc718b75e980e35cafd5fb293cb4/wapc.go#L83
with `return nil, errors.New(strconv.Itoa(int(responseLen)))` and it reports the length is `0`.

I am unable to replicate this behavior with the rust `httpclient`.  At this point, I need help debugging further

**Comment by jordan-rash** [comment] 2021-04-02 19:48
CC: @pkedy

**Comment by autodidaddict** [comment] 2021-04-02 19:50
Is this an issue with the capability provider (written in Rust), or do we think it's with the Go msgpack serialization/deserialization inside the generated http client actor interface?

**Comment by jordan-rash** [comment] 2021-04-02 19:50
I have used both the go based `wapc` and the node based `wapc` with the appropriate codegen.yml and the error reports the same (phil assisted me with this)

**Comment by autodidaddict** [comment] 2021-04-02 19:51
Right but I'm thinking the issue is related to the tinygo actor interface and not the httpclient provider itself?

**Comment by jordan-rash** [comment] 2021-04-02 19:53
> Right but I'm thinking the issue is related to the tinygo actor interface and not the httpclient provider itself?

oh yea, sorry I was just adding more debug steps i took, not replying to you!! Sorry!

**Comment by pkedy** [comment] 2021-04-02 19:53
It may very well be a difference between the Rust/AS/TinyGo worlds. I think we need to understand why the host is returning 0 bytes.  Maybe there is something malformed in the request. I think we need to look at the payloads in the host to diagnose it.

**Comment by brooksmtownsend** [comment] 2021-11-06 12:39
Because we haven't been using TinyGo for a little while, I think this is outdated. Closing for now, and we can re-reference once TinyGo support is back in the future.

**Closed by brooksmtownsend** 2021-11-06 12:39 UTC
Labels: bug
